// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvlglkpfennygfizhzpq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2bGdsa3BmZW5ueWdmaXpoenBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzEyOTksImV4cCI6MjA2NTc0NzI5OX0.E9Vj3GYD0OMyuamwKAe57aJ_qBSLOqf_dqz2ZobGDLM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      storage: localStorage,
    },
    global: {
      headers: {
        'X-Client-Info': 'applynest-ai-forge'
      }
    },
    db: {
      schema: 'public'
    },
    realtime: {
      params: {
        eventsPerSecond: 10
      }
    }
  }
);